import type { Metadata } from "next";
import localFont from "next/font/local";
import "./../globals.css";
import Header from "@/components/Header";
import TopFooter from "@/components/TopFooter";
import Footer from "@/components/Footer";
import Layout from "@/components/Layout";
import SideBar from "@/components/SideBar";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Comforty Ecommerce App",
  description: "Comforty Ecommerce App Generated by create S. M. Shan-e-Ali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout >
            <Header />
                {children}
            <TopFooter />
              <Footer />
              <SideBar />
        <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#000000",
                color: "#FFFFFF",
              },
            }}
          />
        </Layout>
      </body>
    </html>
  );
}
